// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * 
 */
namespace AOGameplayTags
{
	/*AO Initialize State Tags*/
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	/*Initialize State End*/

	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LookUp);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LightAttack);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);

	//UI Layer Put Tag
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_LAYER_MENU);

	//UI Action Binding Tag
	//开启UI需要的按键Tag映射
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_ACTION_ESCAPE);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_ACTION_INVENTORY);



	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_QuickBar);

}
