// Fill out your copyright notice in the Description page of Project Settings.

#pragma once


#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace AOStateTags
{
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Equip_Normal);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_LightAttack);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_CombatWindow);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Combating);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Recovery);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Preparation);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Roll);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Sprint);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Jump);
	AEGISODYSSEY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Block);

}